# Generated by Django 5.2.4 on 2026-06-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Ссылка на аватарку"
            ),
        ),
    ]
